HelpersReference.md, Home.md
Adding documentation of the `chocolateyPackageFolder`, `chocolateyPackageName` and `chocolateyPackageVersion` environment variables made available to `chocolateyInstall.ps1` and `chocolateyUninstall.ps1`.
=> Document chocolateyPackage* variables

HelpersReference.md
Minor bugfix to https://github.com/chocolatey/choco-wiki/pull/2
=> Add missing 'env:' in HelpersReference.md

HelpersInstallChocolateyShortcut.md
HelpersInstallChocolateyShortcut example used an incorrect "workDirectory" parameter instead of "workingDirectory".
=> Fixed working directory parameter in Install-ChocolateyShortcut

CommandsUninstall.md
Explain early on that users most likely need to turn on `autoUninstaller` to remove a package from their system as opposed to simply removing the package from Chocolatey (the default behavior)
=> Reword explanation on uninstalling package from system

FeaturesShim.md
Was getting failures when copy and pasting the code snippet to print the value of $env:ChocolateyInstall. New double quoted syntax works.
$($var) only appears to work inside strings to "resolve" the value of the variable which is why it may work in any Write-* style calls (which technically a string inside "" calls Write-Host if there is no other command in front iirc). See http://stackoverflow.com/a/15113467/3794873
=> Fixed invalid PowerShell syntax in code snippets

DevelopmentEnvironmentSetup.md, ReleaseNotes.md
usage of `-version` produces warning lines in choco. `--version` is the correct parameter name
Fixes #33
=> (GH-33) Instructions for installing specific version are incorrect

AutomaticPackages.md
Ketarin 1.8.7.0 binary or either compiled from
https://cdburnerxp.se/downloads/sourcecode/Ketarin.tar.gz
http://scm.flyspray.org/repos/ketarin/
https://github.com/svn2github/ketarin
support sf urls
```sh
http(s)://sourceforge.net/projects/.../files/latest/download
http(s)://downloads.sourceforge.net/projects/.../...
http(s)://prdownloads.sourceforge.net/projects/.../...
```
isn't it?
=> Ketarin and Sourceforge

CreatePackages.md, CreatePackagesQuickStart.md
Updates docs to make `choco new testpackage` the definitive source of NuGet functionality. Following on from a gitter convo: https://gitter.im/chocolatey/choco?at=5863dec9c02c1a3959c04fff
I haven't made any issue or anything to update/improve https://github.com/chocolatey/chocolateytemplates - which were previously linked as examples, but I removed the example as I thought `choco new` is probable a better source. Will leave that one with you guys - thanks! :-)
=> Use choco new testpackage as definitive source of nuspec options

AutomaticPackages.md
The formatting around this code sample was previously both rendering incorrectly on the website only, and numbering incorrectly on the github wiki (only).
Hopefully this will render and number correctly on both sites! May be worth checking how it comes out on the site, as I'm not sure.
https://chocolatey.org/docs/automatic-packages#setup-1
Thanks guys. :smile:
=> Fix code sample formatting

How-To-Host-Feed.md
Remove mentioning of ProGet being able to be installed using Chocolatey, since that package is broken, Inedo admitted that they haven't touched it since ages and show no interested in fixing it (instead people should build their own scripts)
=> Remove mentioning of ProGet Chocolatey package

Installation.md
Improved the content of the "More Install Options" section, by changing it to a list of different install methods and topics. Also removed content which already exists on other wiki pages or was duplicated on this page.
```
You bet.
Chocolatey will detect and use a system set proxy. However some proxies will need to be set explicitly. To do so, you would do similar to [[Proxy settings for Chocolatey|Proxy-Settings-for-Chocolatey]]
Set the following environment variable(s) prior to install:
* `chocolateyProxyLocation` - explicit proxy location. This includes the port.
* `chocolateyProxyUser` / `chocolateyProxyPassword` - optional credentials
for explicit proxy
In PowerShell, it looks like this:
~~~powershell
$env:chocolateyProxyLocation = 'https://local/proxy/server' …
```
=> (doc) restructure "More Install Options" section

Moderation.md
I happened to be reading this and followed the link to chocolatey/chocolatey.org#308, looks like the future state became the current state 8 months ago and the documentation was left behind. I'm not actually involved in a trusted package workflow but from a quick check of a trusted package, this seems to be the case - but please correct me if I'm wrong.
=> Moderation.md: Update trusted package workflow

CommandsReference.md
Replaced "have chocolatey set it self up" with "have chocolatey set itself up" (i.e. "itself instead of "it self").
=> Fixed typo in CommandsReference.md.

CreatePackages.md
`cpack` has a name collision with `cpack` executable in the CMake package, and
it is going to be removed in Chocolatey v1. Use `choco pack` instead.
=> Change "cpack" to "choco pack"

HelpersGetPackageParameters.md, How-To-Parse-PackageParameters-Argument.md
Fix #75 Variable reference is not valid. ':' was not followed by a valid variable name character.
=> Fix #75 Variable reference is not valid

Installation.md
This is to make the `#installing-to-a-different-location` link work when the user clicks on/follows it.
=> Fix intra-page link

ChocolateyFAQs.md, CreatePackages.md, PackageTriageProcess.md
The current markdown links to the package maintainer handover page
currently have a missing 'i' in the link.
This PR adds that missing 'i' to all instances.
fixes #102
=> (GH-102) Fixed typo in markdown link

Installation.md
The current link only checks packages with ID ending with ".portable". If the package does not have an ".install" version, it will be missed from this link.
Fixes #111.
=> (GH-111) Update link to portable packages

Installation.md
Currently, this section explains how the user’s choice of install location affects the Chocolatey installer in its decision whether to lock down permissions or not.
This PR aims to clarify that explanation in the following ways:
1. State the default location, i. e. `<SYSTEM_DRIVE>:\ProgramData\Chocolatey`; and
2. add an explanation of what _handl\[ing\] \[permissions\] yourself_ is supposed to mean.
Some readers may already know the default location before they get to that section. It might not be their first Choco installation, or they may have seen it being referenced in the PowerShell snippets. That said, I feel that it should not be left to chance whether the reader learns about the default location or not, especially if they wish to do a non-admin install.
=> Explicitly mention the default location

.gitignore, Resources.md
Update the resources section links.
* Remove invalid link in December 2017
* Add a new blog post for April 2019
* Update .gitignore to ignore codealike.* files
=> Update resources section

Resources.md
* Update the resources section with a new community blog post;
* Add a URL link on the name of a previous blog post (rather than having bare URL showing);
=> (GH-126) Update resources section with new blog post

FeaturesAutomaticallyRecompilePackages.md
To fix the invalid URL's:
* Replaced **Getting Started With Chocolatey 4 Business & Jenkins CI** with a new link with similar content;
* Removed **Using Chocolatey in Corporate Environments - Part 1**;
Closes #129
=> (GH-129) Fix invalid urls

Home.md
Fixes the invalid URL on the Docs home page pointing to walkthrough.
Closes #148
=> (GH-148) Fix invalid walkthrough link

Installation.md
The copy button on the installation page used for the chocolatey.org
website is using the "fad" class instead of the "fas" tag. This is
making the icon not appear on the website correctly. The css class has
been updated to the correct "fas" class.
=> (layout) Update css class on copy button

Resources.md
Updates link to Chocolatey Workshop to current link. Also adds link to Organizational Use and Internalizer workshop.
=> Update links to workshops

FeaturesInfrastructureAutomation.md, Home.md, How-To-Recompile-Packages.md, Installation.md, Presentations.md, Resources.md, Roadmap.md
**This PR should be pushed along with https://github.com/chocolatey/chocolatey.org/pull/724**
With the update of using Markdig to convert .md files instead of
Pandoc, a simple change has been made to how the right side navigation
is rendered on chocolatey.org. The look and feel remains the same.
=> (layout) Update right nav for chocolatey.org

Uninstallation.md
The "remove" keyword was missing from the code block on the
uninstallation page. This was causing an extra "-->" to appear when
converted on Chocolatey.org.
=> Add missing "remove" keyword on uninstallation page

FeaturesAgentService.md
A link was using the incorrect format that is not used anywhere else in the repository. When clicking on the link, it takes you to the raw file, and does not work at all on chocolatey.org.
The format has been corrected to how it used throughout the repository, and now works on choco-wiki and on chocolatey.org.
=> (maint) Correct link format

ChocolateyConfiguration.md, FeaturesPackageThrottle.md, Home.md
Two links inside of the documentation have been updated and corrected, as they were broken before on Chocolatey.org.
* /road-map > /roadmap
* /features-package-throttle > /features-download-throttle
=> (maint) Fix broken links

CommandsReference.md
You can see the issue in the second bullet point here:
https://chocolatey.org/docs/commands-reference#scripting-integration-best-practices-style-guide
=> (doc) Fix missing code delimiter

DevelopmentEnvironmentSetup.md
Noticed the h2 wasn't rendering properly at the top of the page [here](https://chocolatey.org/docs/development-environment-setup) - so made a quick tweak to fix it 👍
=> (maint) Fix markdown heading syntax

ChocolateyForBusinessQuickStartGuide.md
Current versions of Nexus block the ability to run scripts, thus causing errors in running the `chocolatey-nexus-setup.nupkg`.  This edit adds a step to enable Nexus scripting, and well as fixing some line breaks around code blocks to ensure linting functions properly.
=> Update QSIG for nexus script changes and indents

ChocolateyForBusinessQuickStartGuide.md
The step in this guide to enable running of scripts on Nexus needs to be moved to one step earlier, otherwise the following steps will break.
=> Update Nexus step order

QuickDeployment/QuickDeploymentDesktopReadme.md
QDE - Small typo of Jenkins port
Listed as port 8081
Should be port 8080
=> QDE - Small typo of Jenkins port

How-To-Setup-Internal-Package-Repository.md
@pauby I know that there was some discussion around the addition of this in the PR that @ryanrichter94 created, but I have tested these scripts, and I can confirm that this option is indeed needed for things to work.
Without this in place, the choco push command fails, since it includes all dependent packages.
The script which syncs the test to chocolatey community repository, or which internalizes a new package, already handles the dependencies on a package.  This script, is only for sync between test to prod repos, so it isn't necessary to download dependencies.
Thoughts?
=> Add ignore dependencies option

CommunityPackagesDisclaimer.md
Updated the text to clarify the reasons a temporary whitelist is given.
Closes #203
=> (GH-203) Clarify why whitelist is given

CentralManagement/CentralManagementDeployments.md
Added a FAQ entry detailing the use of MachineContactTimeout and ExecutionTimeout values in deployment steps for semi-connected environments.
Fix #222
=> (#222) Add FAQ entry for semi-connected setups

CentralManagement/CentralManagementSetupWeb.md
Prior to this commit, we specified that only the
email address field would need to be filled in.
This commit addresses some additonal information that is also required.
Fixes #227
=> (#227) Add additonal details to LDAP configuration documentation

CentralManagement/CentralManagementDeployments.md
Fixes #241 - Use consistent terms for Machine Contact Timeout / Execution Timeout
Units for the properties are more of an implementation detail than a description of what it's for, so I went for the unit-less terms for the documentation. 
Fixes #240 - Updated guidelines around execution timeout to make it clear that it's not really recommended, and a section to common errors & resolutions around handling that eventuality if something stalls.
=> (#240, #241) Update terminology and guidelines for Central Management Deployments

QuickDeployment/V2/QuickDeploymentUpgradeLicense.md
We currently don't have documentation on upgrading a license.
This PR adds documentation with the steps needed to complete this task.
=> (#231) Add license upgrade documentation

CentralManagement/CentralManagementAPI.md
I reconsidered several times on how much detail to include here, but ultimately I think it's probably not a good idea to try to entirely duplicate the Swagger API documentation here, not least because it is likely to change a fair bit between versions.
We can expand this doc in terms of adding a few of the more common use cases and some worked examples for specific scenarios, but for now I figured it's best to get the basics down and a decent summary of API coverage at least, and we can add some specific scenarios as needed.
Resolves #236
=> (#236) Add section for CCM API
