CreatePackages.md
I started just by wanting to fix the quotation marks that kept me from testing my package, but ended up noticing a few other things I could do "drive-by fixes" of.
=> Some changes to the Create Packages docs

Home.md
Add line breaks to Home/Forum/Twitter link.
Convert absolute links to internal reference links (`[[ ]]`)
=> Clean up formatting in Home.md

AutomaticPackages.md
You guys forgot to change this example after changing the name of this tool.
=> Path error in vbs script example

ChocolateyInstallPS1.md, CreatePackages.md
Just a couple of paragraphs about the chocolateyBeforeModify.ps1 script and when it will be triggered.
=> Document modification script

How-To-Install-Upgrade-Package-Without-Scripts.md
=> simple type edit

ChocolateyFAQs.md
Correctly implements https://github.com/chocolatey/chocolatey.org/pull/401/
=> Fix typo (in the right repo)

AutomaticPackages.md
=> Few typo corrections

PackageMantainerHandover.md
Because I really hate fun. 😤
Just kidding. Because it comes through as a broken character on the website version. :smile:  
https://chocolatey.org/docs/package-mantainer-handover
=> Remove emoji

AutomaticPackages.md
Added troubleshooting note about package not being generated when downloaded files are found.
=> Troubleshooting upate

Installation.md
It came up in the Gitter channel today and I couldn't find the quick link to it so I copy and pasted, very icky.
https://gitter.im/chocolatey/choco?at=57ed64766f39416b1cd60564
=> Added quick link to "no internet" install option

How-To-Install-Upgrade-Package-Without-Scripts.md
Changed the **pin** command usage (`choco pin add -n=<package>`)
=> Fix choco pin usage

How-To-Create-Extensions.md
Use chocolatey-core.extension as a sample since chocolatey-uninstallextension is deprecated
=> Use chocolatey-core.extension as a sample

Resources.md
Fixed a broken link for "Running Chocolatey on Linux"
=> Fixed a broken link

CreatePackages.md
* Document details around website icon caching;
* Document reasons for using local caching;
* Document resolution of not being able to see the new icon on the website;
=> (GH-96) Document website icon caching issue

How-To-Setup-Internal-Package-Repository.md
* Corrected internalizer documentation steps;
* Updated the Chocolatey.Server install and configure code;
* Removed formatting bullet points as code;
=> (GH-94) Fix internalizer documentation

How-To-Set-Up-Chocolatey-Server.md
Add PowerShell code to install and configure Chocolatey.Server. Taken from [How To Use Package Internalizer To Create Internal Package Source](https://chocolatey.org/docs/how-to-setup-internal-package-repository#install-and-configure-chocolatey-server).
=> (GH-87) Add PowerShell code

Moderation.md
Deletes an extra double quote mark on lines 79 and 205.
=> Fix typo in Moderation.md

ChocolateyInstallPS1.md, DevelopmentEnvironmentSetup.md
Migrated from https://github.com/chocolatey/chocolatey.org/pull/566
=> (docs) update chocolateyInstall.ps1 URLs

Troubleshooting.md
This PR adds information about registry.bad files and a script that can be used to remediate the issue.
=> (GH-116) Registry.bad section in Troubleshooting.md

Installation.md
Adds optional credentials that can be used to download the Chocolatey nupkg from an authenticated NuGet repository.
Test and working on PS v2+.
Closes #143
=> (GH-143) Add optional credentials for NuGet repository

CreatePackages.md
See https://github.com/chocolatey/choco/issues/1454
=> Clarify windows environment variable usage

Resources.md
Remove Table of Content in floating text
=> Remove Table of Content in floating text

How-To-Mount-An-Iso-In-Chocolatey-Package.md
Add documentation about extension package
This allows users to use the extension to install software
from an ISO file.
=> (GH-153) Add documentation about extension package

Resources.md
* Adds a new blog post to the Jan 2020 section of the Resources section;
* Adds consistency for the whitespace in that section;
=> Add community blog post to the resources section

QuickDeployment/QuickDeploymentDesktopReadme.md, QuickDeployment/QuickDeploymentEnvironment.md, QuickDeployment/QuickDeploymentFirewallChanges.md, QuickDeployment/QuickDeploymentSslSetup.md
- Add title to firewall config page
- Reformat warning blocks a little for clarity
- Fix smiley emoji name
=> Update QDE doc formatting

QuickDeployment/QuickDeploymentSetup.md
QDE: Added to the reference section regarding expanding the `C:` volume. Also included reference to the need to select IDE controller in VMware.
=> add QDE ref to expanding disk, and IDE controller

QuickDeployment/QuickDeploymentDesktopReadme.md
Correct file extension for Nexus error image link
=> Correct file extension for Nexus error image link

CentralManagement/CentralManagementSetupUpgrade.md
This is a first pass at an Upgrade Document for CCM. Please review and change as needed.
=> Add CCM Upgrade doc

How-To-Setup-Internal-Package-Repository.md
This update fixes a problem with dependencies.
* Updates Get-UpdatedPackage.ps1 
* Updates Update-ProdRepoFromTest.ps1
* Updates ConvertTo-ChocoObject.ps1
=> (doc) Update jenkins scripts

Uninstallation.md
Refactored the uninstall script to be a bit easier on the eyes, and a little less clunky in its string manipulation.
- Refactor for readability
- Use verbose instead of output stream
- Refactor PATH string manipulation
=> Refactor uninstallation script in uninstall.md

AutomaticPackages.md
Updated the AU setup instructions according to my experience while following them. Improved some text, removed redundant text, pointed to updated/correct documentation. See the commits messages for isolated changes explanation.
=> Improve AU setup instructions

Troubleshooting.md
Fixes #205 
Adds troubleshooting documentation for identifying and removing a corrupted chocolatey package from a system experiencing a `Root Element Is MIssing` error.
=> (GH-205) Add troubleshooting for 'Root Element Is Missing' error

QuickDeployment/QuickDeploymentSetup.md
Adds the Hyper-V PowerShell module requirements for QDE Azure image.
Closes #208
=> (GH-208) Add Hyper-V PS Module required for Azure

HelpersInstallChocolateyDesktopLink.md
Install-ChocolateyShorctut => Install-ChocolateyShortcut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chocolatey/choco-wiki/211)
=> Correct Typo

QuickDeployment/V2/QuickDeploymentDesktopReadme.md
=> (#220) Add warning that setup should be done from Powershell and NOT the ISE explicitly.

Presentations.md
Add more recent presentations that I know about.
Fixes #218
=> (GH-218) Add recent presentations

How-To-Setup-Offline-Installation.md
Updated offline install link in Step 0 to reflect correct completely offline install page and anchor.
=> Updated offline install link in Step 0

Resources.md
Adds the Octopus and Chocolatey blog post.
Closes #233
=> (GH-233) Add Octopus and Chocolatey blog post
